### ISSUE TITLE
problem using number-recognizer

### ISSUE THREAD

**Issue by gholypur** [mauro-balades/number-recognizer#1]
Hi Dear
I  have problem using number-recognizer. Please help me.

![image](https://user-images.githubusercontent.com/38250630/162141632-d0c6931d-e06e-4333-944e-117efc431c55.png)

**Comment by mauro-balades** [comment]
You spelled recognizer wrong. Change the function class to NumberRecogniser

**Comment by gholypur** [comment]
thank a lot
It seems that the probes remains.

![image](https://user-images.githubusercontent.com/38250630/162245643-329ce630-e61c-4ed5-901f-8eb844899f97.png)

**Comment by mauro-balades** [comment]
```
pip uninstall number_recognition
pip3 install number_recognition
```

**Comment by mauro-balades** [comment]
https://github.com/mauro-balades/number-recognizer/releases/tag/1.0.5

**Comment by gholypur** [comment]
Thanks a lot
If the background of the image was not simple the program does not work.

![problem3](https://user-images.githubusercontent.com/38250630/163328633-a5eea503-bd6f-41ac-b70b-72ef528c0104.png)

**Comment by mauro-balades** [comment]
Think about that as much as you train it more, the better the result. In this case, you only trained it 10 times (which it is the default) meaning that it will recognise ease number. But if you trainit 100 times it can recognize a number made by a 3 year old.


if you want to add more trains, add this:
```
n.init(epochs=100)
```
